### ISSUE TITLE
Issue with "Export figure" on FF 64

### ISSUE THREAD

**Issue by 62mkv** [jjmontesl/cubesviewer#102] opened 2019-01-13 16:56 UTC
Is this expected that View\Export figure suggests you to save a text document titled "Undefined" with a body like 
`data:image/png;base64,iVBORw0KGg...` ?

Happens with me every time for vertical bar chart (at least; didn't try others) on FF 64 Win10 x64

I would rather expect it to save a proper PNG file. 

CubesViewer 2.0.3-devel - Cubes OLAP explorer

**Comment by jjmontesl** [comment] 2019-01-19 03:41
This should be fixed in master (by commit #5ffdbf0).

(It will still take some time to release a next release so you'll have to use the master branch until that).

![image](https://user-images.githubusercontent.com/2786867/51421798-3b00b780-1ba4-11e9-86ed-d85bc19bab91.png)

**Comment by jjmontesl** [comment] 2019-01-19 03:43
Duplicate of #93 .

**Closed as completed by jjmontesl** 2019-01-19 03:43 UTC
Labels: duplicate
