### ISSUE TITLE
Apply dimension filter to dimension filter list to reduce list length

### ISSUE THREAD

**Issue by fpieront** [jjmontesl/cubesviewer#75] opened 2016-06-10 09:06 UTC
I have ~ 150,000 rows distinct on dimension1 in my fact table (total ~ 1 million rows).

I can apply a filter on dimension2, drill down on dimension1 and reduce the result set to ~ 1,500 rows. This works for the results table, so I don't have to increase the row limit. (Dimension2 is hierarchiecally above dimension1).

But this doesn't work for the dimension filter: selecting the filter for dimension1 ALWAYS returns me the full list of records for dimension1 (~150,000), not applying other filters I have set (which would reduce the list of dimension1 values to ~ 1,500). Thus exceeding the row limit of 10k, and many values of dimension1 don't show up in the filter list.

I hope my description was understandable. Can this issue somehow be solved without increasing the row limit of the Cubes server?

**Comment by jjmontesl** [comment] 2016-06-10 22:20
Perfectly understandable. Thanks for the feedback.

I have just checked and the $dimension/members method of Cubes accepts a cut filter. How awesome! I need this.

**Comment by jjmontesl** [comment] 2016-06-12 22:53
Please test feature with latest version.

**Comment by jjmontesl** [comment] 2016-06-13 20:36
Hello! That close/reopen.... any update?

**Comment by jjmontesl** [comment] 2016-06-13 23:36
Note, seems to show repeated elements if there are more than one element filtered on a second dimension.

This seems to be caused by upstream: https://github.com/DataBrewery/cubes/issues/362 .

**Comment by jjmontesl** [comment] 2016-06-14 21:10
Ok, great to confirm that. I'll keep this open for a while until I know about a possible resolution upstream (I could artificially remove duplicates in CV but I'd rather avoid hacking that). I might eventually close this before resolution, though.

Thanks for your valuable contributions.

**Comment by voldesh** [comment] 2016-06-27 07:02
Can you give an example query to show 25 records ordered by date ?

**Comment by jjmontesl** [comment] 2016-07-02 13:40
This has been fixed on Cubes master (https://github.com/DataBrewery/cubes/issues/362), so I'm closing this.

**Closed by jjmontesl** 2016-07-02 13:40 UTC
Labels: enhancement
